name: Build APK from ZIP
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Unzip
        run: sudo apt-get install unzip
      - name: Unzip Project
        run: unzip z_learn.zip
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install Cordova
        run: npm install -g cordova
      - name: Build Android
        run: |
          cordova platform add android@12.0.0
          cordova build android --release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: My-App-APK
          path: platforms/android/app/build/outputs/apk/release/*.apk
